### ISSUE TITLE
[积累][Spring] Web Filter 使用 DelegatingFilterProxy 的原因

### ISSUE THREAD

**Issue by fxleyu** [fxleyu/precious-deposits#147]
```
	at fx.leyu.tracer.filter.UserTraceFilter.doFilter(UserTraceFilter.java:65)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
```

**Comment by fxleyu** [comment]
https://blog.csdn.net/xiaobudaics/article/details/51566804
