### ISSUE TITLE
[Spring] 构造器中使用 @Autowired 中的属性报空指针

### ISSUE THREAD

**Issue by fxleyu** [fxleyu/precious-deposits#159]
```java
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.jd.app.server.mixer.service.linkage.LinkageService com.jd.app.server.mixer.service.impl.MixerServiceImpl.linkageService; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'linkageServiceImpl' defined in URL [jar:file:/export/Packages/indivsoa.care/20190517185142/WEB-INF/lib/mixer-service-3.0.0.linkage-20190517.103603-2.jar!/com/jd/app/server/mixer/service/linkage/impl/LinkageServiceImpl.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.jd.app.server.mixer.service.linkage.impl.LinkageServiceImpl]: Constructor threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:555)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:87)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 111 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'linkageServiceImpl' defined in URL [jar:file:/export/Packages/indivsoa.care/20190517185142/WEB-INF/lib/mixer-service-3.0.0.linkage-20190517.103603-2.jar!/com/jd/app/server/mixer/service/linkage/impl/LinkageServiceImpl.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.jd.app.server.mixer.service.linkage.impl.LinkageServiceImpl]: Constructor threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1095)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1040)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:505)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:229)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:298)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1127)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1051)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:949)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:527)
	... 113 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.jd.app.server.mixer.service.linkage.impl.LinkageServiceImpl]: Constructor threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:89)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1088)
	... 124 more
Caused by: java.lang.NullPointerException
	at com.jd.app.server.mixer.service.linkage.impl.LinkageServiceImpl.updateBlackList(LinkageServiceImpl.java:44)
	at com.jd.app.server.mixer.service.linkage.impl.LinkageServiceImpl.<init>(LinkageServiceImpl.java:36)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
	... 126 more
```

**Comment by fxleyu** [comment]
```java
    @PostConstruct
    public void init/*LinkageServiceImpl*/() {
        updateBlackList();
        long initialDelay = RandomUtils.nextInt((int)SECOND_OF_DELAY_BLACK_LIST, 2 * (int)SECOND_OF_DELAY_BLACK_LIST);
        ScheduledExecutorService scheduledExecutorService = Executors.newSingleThreadScheduledExecutor();
        scheduledExecutorService.scheduleWithFixedDelay(this::updateBlackList,
                initialDelay, SECOND_OF_DELAY_BLACK_LIST, TimeUnit.MINUTES);
    }
```
