### ISSUE TITLE
[死锁] 一次死锁的堆栈信息

### ISSUE THREAD

**Issue by fxleyu** [fxleyu/precious-deposits#234]
```
2019-09-01 22:04:23
Full thread dump Java HotSpot(TM) 64-Bit Server VM (9.0.1+11 mixed mode):

"DestroyJavaVM" #16 prio=5 os_prio=0 tid=0x0000019342a65000 nid=0x3394 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Thread-1" #14 prio=5 os_prio=0 tid=0x000001936661c800 nid=0x3c1c in Object.wait() [0x0000001567eff000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@9.0.1/Native Method)
	- waiting on <0x0000000088fb3f48> (a java.lang.Object)
	at java.lang.Object.wait(java.base@9.0.1/Object.java:516)
	at fx.leyu.leetcode.top1101to1150.problem14.Foo.second(Foo.java:20)
	- waiting to re-lock in wait() <0x0000000088fb3f48> (a java.lang.Object)
	at fx.leyu.leetcode.top1101to1150.problem14.Main.lambda$main$3(Main.java:15)
	at fx.leyu.leetcode.top1101to1150.problem14.Main$$Lambda$2/357863579.run(Unknown Source)
	at java.lang.Thread.run(java.base@9.0.1/Thread.java:844)

"Thread-0" #13 prio=5 os_prio=0 tid=0x0000019366618000 nid=0x1358 in Object.wait() [0x0000001567dfe000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@9.0.1/Native Method)
	- waiting on <0x0000000088fb3f58> (a java.lang.Object)
	at java.lang.Object.wait(java.base@9.0.1/Object.java:516)
	at fx.leyu.leetcode.top1101to1150.problem14.Foo.third(Foo.java:31)
	- waiting to re-lock in wait() <0x0000000088fb3f58> (a java.lang.Object)
	at fx.leyu.leetcode.top1101to1150.problem14.Main.lambda$main$1(Main.java:8)
	at fx.leyu.leetcode.top1101to1150.problem14.Main$$Lambda$1/249515771.run(Unknown Source)
	at java.lang.Thread.run(java.base@9.0.1/Thread.java:844)

"Service Thread" #12 daemon prio=9 os_prio=0 tid=0x000001936662f000 nid=0x2a14 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Monitor Ctrl-Break" #11 daemon prio=5 os_prio=0 tid=0x0000019366632800 nid=0x1110 runnable [0x0000001567afe000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(java.base@9.0.1/Native Method)
	at java.net.SocketInputStream.socketRead(java.base@9.0.1/SocketInputStream.java:116)
	at java.net.SocketInputStream.read(java.base@9.0.1/SocketInputStream.java:171)
	at java.net.SocketInputStream.read(java.base@9.0.1/SocketInputStream.java:141)
	at sun.nio.cs.StreamDecoder.readBytes(java.base@9.0.1/StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(java.base@9.0.1/StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(java.base@9.0.1/StreamDecoder.java:178)
	- locked <0x0000000088e5bc40> (a java.io.InputStreamReader)
	at java.io.InputStreamReader.read(java.base@9.0.1/InputStreamReader.java:185)
	at java.io.BufferedReader.fill(java.base@9.0.1/BufferedReader.java:161)
	at java.io.BufferedReader.readLine(java.base@9.0.1/BufferedReader.java:326)
	- locked <0x0000000088e5bc40> (a java.io.InputStreamReader)
	at java.io.BufferedReader.readLine(java.base@9.0.1/BufferedReader.java:392)
	at com.intellij.rt.execution.application.AppMainV2$1.run(AppMainV2.java:64)

"Common-Cleaner" #10 daemon prio=8 os_prio=1 tid=0x000001936632a800 nid=0x15d4 in Object.wait() [0x00000015679fe000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@9.0.1/Native Method)
	- waiting on <0x00000000893b81e8> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@9.0.1/ReferenceQueue.java:151)
	- waiting to re-lock in wait() <0x00000000893b81e8> (a java.lang.ref.ReferenceQueue$Lock)
	at jdk.internal.ref.CleanerImpl.run(java.base@9.0.1/CleanerImpl.java:148)
	at java.lang.Thread.run(java.base@9.0.1/Thread.java:844)
	at jdk.internal.misc.InnocuousThread.run(java.base@9.0.1/InnocuousThread.java:122)

"Sweeper thread" #9 daemon prio=9 os_prio=2 tid=0x000001936620f800 nid=0x4a90 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread2" #8 daemon prio=9 os_prio=2 tid=0x0000019366204800 nid=0x37e0 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"C2 CompilerThread1" #7 daemon prio=9 os_prio=2 tid=0x0000019366200800 nid=0x3300 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"C2 CompilerThread0" #6 daemon prio=9 os_prio=2 tid=0x00000193661fb800 nid=0x371c waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"Attach Listener" #5 daemon prio=5 os_prio=2 tid=0x00000193661f6800 nid=0x3954 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=2 tid=0x00000193661f5800 nid=0x2ca4 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=1 tid=0x000001936619d800 nid=0x47a0 in Object.wait() [0x00000015672ff000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@9.0.1/Native Method)
	- waiting on <0x000000008930d000> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@9.0.1/ReferenceQueue.java:151)
	- waiting to re-lock in wait() <0x000000008930d000> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@9.0.1/ReferenceQueue.java:172)
	at java.lang.ref.Finalizer$FinalizerThread.run(java.base@9.0.1/Finalizer.java:216)

"Reference Handler" #2 daemon prio=10 os_prio=2 tid=0x0000019366193000 nid=0xc90 waiting on condition [0x00000015671ff000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.ref.Reference.waitForReferencePendingList(java.base@9.0.1/Native Method)
	at java.lang.ref.Reference.processPendingReferences(java.base@9.0.1/Reference.java:174)
	at java.lang.ref.Reference.access$000(java.base@9.0.1/Reference.java:44)
	at java.lang.ref.Reference$ReferenceHandler.run(java.base@9.0.1/Reference.java:138)

"VM Thread" os_prio=2 tid=0x000001936617d800 nid=0x4100 runnable 

"GC Thread#0" os_prio=2 tid=0x0000019342a7a800 nid=0x2d4c runnable 

"GC Thread#1" os_prio=2 tid=0x0000019342a7c000 nid=0xc58 runnable 

"GC Thread#2" os_prio=2 tid=0x0000019342a7f000 nid=0x2498 runnable 

"GC Thread#3" os_prio=2 tid=0x0000019342a85000 nid=0x4288 runnable 

"G1 Main Marker" os_prio=2 tid=0x0000019342b01800 nid=0xdf4 runnable 

"G1 Marker#0" os_prio=2 tid=0x0000019342b06000 nid=0x1b90 runnable 

"G1 Refine#0" os_prio=2 tid=0x0000019342a91800 nid=0x1d18 runnable 

"G1 Refine#1" os_prio=2 tid=0x0000019342a90800 nid=0x6f0 runnable 

"G1 Refine#2" os_prio=2 tid=0x0000019342a8b800 nid=0x2488 runnable 

"G1 Refine#3" os_prio=2 tid=0x0000019342a8a800 nid=0x9e8 runnable 

"G1 Young RemSet Sampling" os_prio=2 tid=0x0000019342a9a800 nid=0x41f8 runnable 

"VM Periodic Task Thread" os_prio=2 tid=0x0000019366610000 nid=0x3540 waiting on condition 

JNI global references: 144

Heap
 garbage-first heap   total 131072K, used 7168K [0x0000000081400000, 0x0000000081500400, 0x0000000100000000)
  region size 1024K, 8 young (8192K), 0 survivors (0K)
 Metaspace       used 6173K, capacity 6328K, committed 6528K, reserved 1056768K
  class space    used 533K, capacity 570K, committed 640K, reserved 1048576K
```

**Comment by fxleyu** [comment]
# 源码
```java
// Foo.java
public class Foo {
    private final static Object TWO = new Object();
    private final static Object THREE = new Object();

    public Foo() {
    }

    public void first(Runnable printFirst) throws InterruptedException {
        // printFirst.run() outputs "first". Do not change or remove this line.
        printFirst.run();
        synchronized (TWO) {
            TWO.notify();
        }
    }

    public void second(Runnable printSecond) throws InterruptedException {
        synchronized (TWO) {
            TWO.wait();
        }
        // printSecond.run() outputs "second". Do not change or remove this line.
        printSecond.run();
        synchronized (THREE) {
            THREE.notify();
        }
    }

    public void third(Runnable printThird) throws InterruptedException {
        synchronized (THREE) {
            THREE.wait();
        }
        // printThird.run() outputs "third". Do not change or remove this line.
        printThird.run();
    }
}
```

```java
// Main.java
public class Main {
    public static void main(String[] args) {
        Foo foo = new Foo();
        new Thread(() -> {
            try {
                foo.third(() -> System.out.print("three"));
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }).start();
        new Thread(() -> {
            try {
                foo.second(() -> System.out.print("two"));
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }).start();
        new Thread(() -> {
            try {
                foo.first(() -> System.out.print("one"));
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }).start();
    }
}
```

**Comment by fxleyu** [comment]
# 死锁原因
线程3运行玩了，线程2还没有开始运行
