### ISSUE TITLE
[Exception] BeanNotOfRequiredTypeException

### ISSUE THREAD

**Issue by fxleyu** [fxleyu/precious-deposits#265]
```java
Caused by: org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'accountCacheService' is expected to be of type 'x.AccountCacheService' but was actually of type 'x.AccountSoloCacheClient'

at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:389)

at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204)

at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.autowireResource(CommonAnnotationBeanPostProcessor.java:514)

at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.getResource(CommonAnnotationBeanPostProcessor.java:485)

at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement.getResourceToInject(CommonAnnotationBeanPostProcessor.java:619)

at org.springframework.beans.factory.annotation.InjectionMetadata$InjectedElement.inject(InjectionMetadata.java:180)

at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)

at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessPropertyValues(CommonAnnotationBeanPostProcessor.java:318)
```

**Comment by fxleyu** [comment]
解决方案：
```java
@Resource(name = "frontAccountCacheService")
@Service("frontAccountCacheService")
```
