### ISSUE TITLE
[问题][Redis] 处理访问 Redis 服务器出现 Connection refused: connect

### ISSUE THREAD

**Issue by fxleyu** [fxleyu/precious-deposits#49]
Java 代码如下：
```java
public class HelloString {
    public static void main(String[] args) {
        JedisPool pool = new JedisPool(new JedisPoolConfig(), "192.168.199.120");
        try (Jedis jedis = pool.getResource()) {
            jedis.set("hello", "world");
        }
    }
}
```

但出现如下异常，很确定 Redis 服务器起来了。
```
Exception in thread "main" redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.util.Pool.getResource(Pool.java:53)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:226)
	at fx.leyu.redis.string.HelloString.main(HelloString.java:10)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused: connect
	at redis.clients.jedis.Connection.connect(Connection.java:207)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:93)
	at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1767)
	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:106)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:868)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:435)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
	at redis.clients.util.Pool.getResource(Pool.java:49)
	... 2 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.base/java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.base/java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:400)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:243)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:225)
	at java.base/java.net.PlainSocketImpl.connect(PlainSocketImpl.java:148)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:402)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at redis.clients.jedis.Connection.connect(Connection.java:184)
	... 9 more

```

**Comment by fxleyu** [comment]
# 关于连接被拒绝的思考
出现了 `Connection refused: connect`，可能 Redis 服务器对外访问端口未打开。但，使用 redis-cli 时，明确端口是打开的，信息如下：
![image](https://user-images.githubusercontent.com/3362121/42726206-042afcea-87c3-11e8-8754-461514107f0c.png)

排除网络端口问题，百度答案。

**Comment by fxleyu** [comment]
# 解决方案
- 修改 ` /etc/redis/redis.conf` 文件，注释掉 `bind 127.0.0.1`; `sudo vi /etc/redis/redis.conf`
- 重启 Redis 服务; `/etc/init.d/redis-server restart`
- OK

## 百度查询的资料
- [无法访问的问题](https://blog.csdn.net/yinbucheng/article/details/76098587)
- [Redis 重新启动的问题](https://www.cnblogs.com/GoQC/p/5764201.html)
